version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: 99tech-be
    ports:
      - 3000:3000
    restart: unless-stopped
    env_file: .env
    networks:
      - backend-network
    depends_on:
      - db

  db:
    platform: linux/x86_64
    image: mysql:8.0.28
    container_name: db
    ports:
      - 3006:3306
    restart: unless-stopped
    env_file: .env
    volumes:
      - volume-db:/var/lib/mysql
    networks:
      - backend-network
volumes:
  volume-db:
networks:
  backend-network:
